port: 3001
cluster: true
websocket: false
mqttServer: mqtt://localhost
logdir: storage
exceptionFilename: exceptions.log
exceptionFilesize: 10M
exceptionBackups: 100
appLogLevel: warn
appLogSize: 31457280
database:
  storage: database.sqlite
session:
  secrets: abcd.1234
ota:
  firmwareDir: storage/firmwares
sysadmin:
  username: sysadmin
  password: sysadmin
