port: 3001
cluster: true
websocket: false
mqtt:
  brokerUrl: mqtt://localhost
logdir: storage
appLogLevel: warn
appLogSize: 31457280
database:
  storage: database.sqlite
session:
  secrets: abcd.1234
ota:
  firmwareDir: storage/firmwares
sysadmin:
  username: sysadmin
  password: sysadmin
maxUploadFileSize: 209715200
