port: 3001
cluster: true
mqtt:
  brokerUrl: mqtt://localhost
storage: storage
appLogLevel: warn
appLogSize: 31457280
dbUrl: mongodb://localhost/logactivate
session:
  secrets: abcd.1234
sysadmin:
  username: sysadmin
  password: sysadmin
maxUploadFileSize: 209715200
