port: 3001
cluster: true
websocket: false
mqtt:
  brokerUrl: mqtt://localhost
storage: storage
appLogLevel: warn
appLogSize: 31457280
database:
  storage: database.sqlite
session:
  secrets: abcd.1234
sysadmin:
  username: sysadmin
  password: sysadmin
maxUploadFileSize: 209715200
