port: 3001
cluster: true
logdir: storage
exceptionFilename: exceptions.log
exceptionFilesize: 1M
exceptionBackups: 100
appLogFilename: logactivate.log
appLogLevel: warn
appLogSize: 31457280
database:
  storage: database.sqlite
  host: localhost
  dialect: sqlite
  operatorsAliases: false
session:
  secrets: abcd.1234
  maxAge: '24h'
ota:
  firmwareDir: storage/firmwares
users:
  sysadmin:
    level: 0
    password: sysadmin
